### PR TITLE
changed speed indicator bar (slider) and changed speed keys to plus (+) and minus (-)

### PR DESCRIPTION
**Pull request by gpunktschmitz**

### CODE REVIEW

**Comment by noqqe** [comment]
looks good to me :) thanks!

**Comment by noqqe** [comment]
except that it does not work ... :D did the checkout on nicht.parasoup.de ... please try and have a second look!

**Comment by gpunktschmitz** [comment]
i checked the current state on nicht.parasoup.de and it works on linux 
(chromimum/firefox/opera) and on windows (chrome/firefox/opera) .. which 
os/browser does not work?

**Comment by noqqe** [comment]
Are you using Numpad + and - ?

**Comment by noqqe** [comment]
Im Using Chrome/Safari on OSX

**Comment by gpunktschmitz** [comment]
i do .. i do ...
i will look into this.

**Comment by jkowalleck** [comment]
why not use "f" and "j" for the speed?
they are easy to find in the dark (thanks to the marks for the fingers) and are much easier to implement in the existing code ;-)

**Pull request merged**
