### PR TITLE
2.0 dev reverse proxy

### PR DESCRIPTION
**Pull request by jkowalleck**

### CODE REVIEW

**Comment by noqqe** [comment]
Can you explain to me why this is necessary? 

```
  proxy:
    x_for: 1     # Number of values to trust for X-Forwarded-For.
    x_proto: 1   # Number of values to trust for X-Forwarded-Proto.
    x_host: 1    # Number of values to trust for X-Forwarded-Host.
    x_port: 1    # Number of values to trust for X-Forwarded-Port.
    x_prefix: 1  # Number of values to trust for X-Forwarded-Prefix.
```
I reads like this is some kind of security measure but to be honest i really cannot think of an attack scenario here and would prefer to remove this

**Comment by jkowalleck** [comment]
@noqqe 

in reply to https://github.com/k4cg/nichtparasoup/pull/155#issuecomment-553304571
this was done because of this:
> When an application is running behind a proxy server, WSGI may see the request as coming from that server rather than
> the real client. Proxies set various headers to track where the request actually came from.  
> \[The `proxy` settings\] should be configured with the number of proxies that are chained in front of it. Not all proxies set all the
> headers. Since incoming headers can be faked, you must set how many proxies are setting each header so the middleware 
> knows what to trust.

**Comment by jkowalleck** [comment]
@noqqe works for me.
could you see it it also works in your setup?

**Comment by noqqe** [comment]
Does the job, i love it <3

**Comment by jkowalleck** [comment]
Lets quash merge it

**Pull request merged**
