### PR TITLE
some pmrovements, fixed 9gag, etc

### PR DESCRIPTION
**Pull request by jkowalleck**
multiple imrovements: 

fixed crawler for ninegag

CONF: imporved config
* added `config.defaults.ini`
* improved `config.ini`
* chose better default values

NP: `nichtparasoup.py` now has command line arguments
try `-h` for details

NP: `nichtparasoup.py` improved config behaviours
* read `config.defaults.ini` first, then a custom config
* custom config may be set via comamnd line argument `-c`
* custom config defaults to `config.ini`

CRAWL: renamed some config accessors in the crawler
* renamed: `headers()` -> `reques_theaders()`
* renamed: `timeout()` -> `request_timeout()`
* added several doc strings

CRAWL: convinience methods for fetching remote data
* added `_fetch_remote()`
* added `_fetch_remote_html()`
* used these functions where ever possible

CRAWL: improved error handling
* added multiple fail-over tests on variables
* added multiple fail-over tests on function calls
* added multiple logging entries on DEBUG level

TEST: added prepared custom inis for testing in `tests/configs/`

cleaned up unused imports on several places

### CODE REVIEW

**Comment by noqqe** [comment]
this is a very...brief description for this big changes

**Comment by jkowalleck** [comment]
wait with the merge a bit, maybe i will add some tests and stuff soon

**Comment by jkowalleck** [comment]
i think this should be reviewed carefully.

**Comment by noqqe** [comment]
carefully?

**Pull request merged**
